import { globSync } from "glob";

const qs = [
  "3442. Maximum Difference Between Even and Odd Frequency I",
  "1. Two Sum",
  "2. Add Two Numbers",
  "3. Longest Substring Without Repeating Characters",
  "4. Median of Two Sorted Arrays",
  "5. Longest Palindromic Substring",
  "6. Zigzag Conversion",
  "7. Reverse Integer",
  "8. String to Integer (atoi)",
  "9. Palindrome Number",
  "10. Regular Expression Matching",
  "11. Container With Most Water",
  "12. Integer to Roman",
  "13. Roman to Integer",
  "14. Longest Common Prefix",
  "15. 3Sum",
  "16. 3Sum Closest",
  "17. Letter Combinations of a Phone Number",
  "18. 4Sum",
  "19. Remove Nth Node From End of List",
  "20. Valid Parentheses",
  "21. Merge Two Sorted Lists",
  "22. Generate Parentheses",
  "23. Merge k Sorted Lists",
  "24. Swap Nodes in Pairs",
  "25. Reverse Nodes in k-Group",
  "26. Remove Duplicates from Sorted Array",
  "27. Remove Element",
  "28. Find the Index of the First Occurrence in a String",
  "29. Divide Two Integers",
  "30. Substring with Concatenation of All Words",
  "31. Next Permutation",
  "32. Longest Valid Parentheses",
  "33. Search in Rotated Sorted Array",
  "34. Find First and Last Position of Element in Sorted Array",
  "35. Search Insert Position",
  "36. Valid Sudoku",
  "37. Sudoku Solver",
  "38. Count and Say",
  "39. Combination Sum",
  "40. Combination Sum II",
  "41. First Missing Positive",
  "42. Trapping Rain Water",
  "43. Multiply Strings",
  "44. Wildcard Matching",
  "45. Jump Game II",
  "46. Permutations",
  "47. Permutations II",
  "48. Rotate Image",
  "49. Group Anagrams",
  "50. Pow(x, n)",
  "51. N-Queens",
  "52. N-Queens II",
  "53. Maximum Subarray",
  "54. Spiral Matrix",
  "55. Jump Game",
  "56. Merge Intervals",
  "57. Insert Interval",
  "58. Length of Last Word",
  "59. Spiral Matrix II",
  "60. Permutation Sequence",
  "61. Rotate List",
  "62. Unique Paths",
  "63. Unique Paths II",
  "64. Minimum Path Sum",
  "65. Valid Number",
  "66. Plus One",
  "67. Add Binary",
  "68. Text Justification",
  "69. Sqrt(x)",
  "70. Climbing Stairs",
  "71. Simplify Path",
  "72. Edit Distance",
  "73. Set Matrix Zeroes",
  "74. Search a 2D Matrix",
  "75. Sort Colors",
  "76. Minimum Window Substring",
  "77. Combinations",
  "78. Subsets",
  "79. Word Search",
  "80. Remove Duplicates from Sorted Array II",
  "81. Search in Rotated Sorted Array II",
  "82. Remove Duplicates from Sorted List II",
  "83. Remove Duplicates from Sorted List",
  "84. Largest Rectangle in Histogram",
  "85. Maximal Rectangle",
  "86. Partition List",
  "87. Scramble String",
  "88. Merge Sorted Array",
  "89. Gray Code",
  "90. Subsets II",
  "91. Decode Ways",
  "92. Reverse Linked List II",
  "93. Restore IP Addresses",
  "94. Binary Tree Inorder Traversal",
  "95. Unique Binary Search Trees II",
  "96. Unique Binary Search Trees",
  "97. Interleaving String",
  "98. Validate Binary Search Tree",
  "99. Recover Binary Search Tree",
  "100. Same Tree",
  "101. Symmetric Tree",
  "102. Binary Tree Level Order Traversal",
  "103. Binary Tree Zigzag Level Order Traversal",
  "104. Maximum Depth of Binary Tree",
  "105. Construct Binary Tree from Preorder and Inorder Traversal",
  "106. Construct Binary Tree from Inorder and Postorder Traversal",
  "107. Binary Tree Level Order Traversal II",
  "108. Convert Sorted Array to Binary Search Tree",
  "109. Convert Sorted List to Binary Search Tree",
  "110. Balanced Binary Tree",
  "111. Minimum Depth of Binary Tree",
  "112. Path Sum",
  "113. Path Sum II",
  "114. Flatten Binary Tree to Linked List",
  "115. Distinct Subsequences",
  "116. Populating Next Right Pointers in Each Node",
  "117. Populating Next Right Pointers in Each Node II",
  "118. Pascal's Triangle",
  "119. Pascal's Triangle II",
  "120. Triangle",
  "121. Best Time to Buy and Sell Stock",
  "122. Best Time to Buy and Sell Stock II",
  "123. Best Time to Buy and Sell Stock III",
  "124. Binary Tree Maximum Path Sum",
  "125. Valid Palindrome",
  "126. Word Ladder II",
  "127. Word Ladder",
  "128. Longest Consecutive Sequence",
  "129. Sum Root to Leaf Numbers",
  "130. Surrounded Regions",
  "131. Palindrome Partitioning",
  "133. Clone Graph",
  "134. Gas Station",
  "135. Candy",
  "136. Single Number",
  "137. Single Number II",
  "138. Copy List with Random Pointer",
  "139. Word Break",
  "140. Word Break II",
  "141. Linked List Cycle",
  "142. Linked List Cycle II",
  "143. Reorder List",
  "144. Binary Tree Preorder Traversal",
  "145. Binary Tree Postorder Traversal",
  "146. LRU Cache",
  "147. Insertion Sort List",
  "148. Sort List",
  "149. Max Points on a Line",
  "150. Evaluate Reverse Polish Notation",
  "151. Reverse Words in a String",
  "152. Maximum Product Subarray",
  "153. Find Minimum in Rotated Sorted Array",
  "154. Find Minimum in Rotated Sorted Array II",
  "155. Min Stack",
  "160. Intersection of Two Linked Lists",
  "162. Find Peak Element",
  "165. Compare Version Numbers",
  "166. Fraction to Recurring Decimal",
  "167. Two Sum II - Input Array Is Sorted",
  "168. Excel Sheet Column Title",
  "169. Majority Element",
  "171. Excel Sheet Column Number",
  "172. Factorial Trailing Zeroes",
  "174. Dungeon Game",
  "175. Combine Two Tables",
  "179. Largest Number",
  "189. Rotate Array",
  "190. Reverse Bits",
  "191. Number of 1 Bits",
  "197. Rising Temperature",
  "198. House Robber",
  "199. Binary Tree Right Side View",
  "200. Number of Islands",
  "201. Bitwise AND of Numbers Range",
  "202. Happy Number",
  "206. Reverse Linked List",
  "207. Course Schedule",
  "208. Implement Trie (Prefix Tree)",
  "210. Course Schedule II",
  "211. Design Add and Search Words Data Structure",
  "212. Word Search II",
  "213. House Robber II",
  "215. Kth Largest Element in an Array",
  "217. Contains Duplicate",
  "218. The Skyline Problem",
  "221. Maximal Square",
  "222. Count Complete Tree Nodes",
  "224. Basic Calculator",
  "226. Invert Binary Tree",
  "227. Basic Calculator II",
  "228. Summary Ranges",
  "230. Kth Smallest Element in a BST",
  "231. Power of Two",
  "232. Implement Queue using Stacks",
  "234. Palindrome Linked List",
  "235. Lowest Common Ancestor of a Binary Search Tree",
  "236. Lowest Common Ancestor of a Binary Tree",
  "237. Delete Node in a Linked List",
  "238. Product of Array Except Self",
  "239. Sliding Window Maximum",
  "240. Search a 2D Matrix II",
  "242. Valid Anagram",
  "258. Add Digits",
  "260. Single Number III",
  "268. Missing Number",
  "278. First Bad Version",
  "279. Perfect Squares",
  "282. Expression Add Operators",
  "283. Move Zeroes",
  "287. Find the Duplicate Number",
  "289. Game of Life",
  "290. Word Pattern",
  "295. Find Median from Data Stream",
  "297. Serialize and Deserialize Binary Tree",
  "300. Longest Increasing Subsequence",
  "309. Best Time to Buy and Sell Stock with Cooldown",
  "310. Minimum Height Trees",
  "315. Count of Smaller Numbers After Self",
  "318. Maximum Product of Word Lengths",
  "319. Bulb Switcher",
  "322. Coin Change",
  "326. Power of Three",
  "328. Odd Even Linked List",
  "329. Longest Increasing Path in a Matrix",
  "330. Patching Array",
  "331. Verify Preorder Serialization of a Binary Tree",
  "334. Increasing Triplet Subsequence",
  "337. House Robber III",
  "338. Counting Bits",
  "341. Flatten Nested List Iterator",
  "342. Power of Four",
  "344. Reverse String",
  "345. Reverse Vowels of a String",
  "347. Top K Frequent Elements",
  "349. Intersection of Two Arrays",
  "350. Intersection of Two Arrays II",
  "367. Valid Perfect Square",
  "371. Sum of Two Integers",
  "374. Guess Number Higher or Lower",
  "380. Insert Delete GetRandom O(1)",
  "383. Ransom Note",
  "384. Shuffle an Array",
  "386. Lexicographical Numbers",
  "387. First Unique Character in a String",
  "389. Find the Difference",
  "392. Is Subsequence",
  "394. Decode String",
  "395. Longest Substring with At Least K Repeating Characters",
  "404. Sum of Left Leaves",
  "412. Fizz Buzz",
  "415. Add Strings",
  "416. Partition Equal Subset Sum",
  "417. Pacific Atlantic Water Flow",
  "424. Longest Repeating Character Replacement",
  "430. Flatten a Multilevel Doubly Linked List",
  "435. Non-overlapping Intervals",
  "437. Path Sum III",
  "438. Find All Anagrams in a String",
  "440. K-th Smallest in Lexicographical Order",
  "442. Find All Duplicates in an Array",
  "443. String Compression",
  "446. Arithmetic Slices II - Subsequence",
  "448. Find All Numbers Disappeared in an Array",
  "451. Sort Characters By Frequency",
  "454. 4Sum II",
  "461. Hamming Distance",
  "463. Island Perimeter",
  "476. Number Complement",
  "485. Max Consecutive Ones",
  "486. Predict the Winner",
  "494. Target Sum",
  "496. Next Greater Element I",
  "509. Fibonacci Number",
  "530. Minimum Absolute Difference in BST",
  "532. K-diff Pairs in an Array",
  "540. Single Element in a Sorted Array",
  "543. Diameter of Binary Tree",
  "560. Subarray Sum Equals K",
  "563. Binary Tree Tilt",
  "565. Array Nesting",
  "567. Permutation in String",
  "572. Subtree of Another Tree",
  "584. Find Customer Referee",
  "587. Erect the Fence",
  "595. Big Countries",
  "605. Can Place Flowers",
  "606. Construct String from Binary Tree",
  "617. Merge Two Binary Trees",
  "623. Add One Row to Tree",
  "643. Maximum Average Subarray I",
  "647. Palindromic Substrings",
  "649. Dota2 Senate",
  "653. Two Sum IV - Input is a BST",
  "657. Robot Return to Origin",
  "670. Maximum Swap",
  "695. Max Area of Island",
  "698. Partition to K Equal Sum Subsets",
  "701. Insert into a Binary Search Tree",
  "704. Binary Search",
  "714. Best Time to Buy and Sell Stock with Transaction Fee",
  "724. Find Pivot Index",
  "725. Split Linked List in Parts",
  "739. Daily Temperatures",
  "744. Find Smallest Letter Greater Than Target",
  "746. Min Cost Climbing Stairs",
  "763. Partition Labels",
  "764. Largest Plus Sign",
  "771. Jewels and Stones",
  "781. Rabbits in Forest",
  "782. Transform to Chessboard",
  "783. Minimum Distance Between BST Nodes",
  "790. Domino and Tromino Tiling",
  "834. Sum of Distances in Tree",
  "838. Push Dominoes",
  "839. Similar String Groups",
  "848. Shifting Letters",
  "852. Peak Index in a Mountain Array",
  "863. All Nodes Distance K in Binary Tree",
  "867. Transpose Matrix",
  "876. Middle of the Linked List",
  "877. Stone Game",
  "878. Nth Magical Number",
  "881. Boats to Save People",
  "882. Reachable Nodes In Subdivided Graph",
  "889. Construct Binary Tree from Preorder and Postorder Traversal",
  "890. Find and Replace Pattern",
  "899. Orderly Queue",
  "917. Reverse Only Letters",
  "921. Minimum Add to Make Parentheses Valid",
  "922. Sort Array By Parity II",
  "929. Unique Email Addresses",
  "930. Binary Subarrays With Sum",
  "938. Range Sum of BST",
  "946. Validate Stack Sequences",
  "951. Flip Equivalent Binary Trees",
  "973. K Closest Points to Origin",
  "974. Subarray Sums Divisible by K",
  "978. Longest Turbulent Subarray",
  "980. Unique Paths III",
  "983. Minimum Cost For Tickets",
  "986. Interval List Intersections",
  "993. Cousins in Binary Tree",
  "994. Rotting Oranges",
  "1004. Max Consecutive Ones III",
  "1007. Minimum Domino Rotations For Equal Row",
  "1008. Construct Binary Search Tree from Preorder Traversal",
  "1009. Complement of Base 10 Integer",
  "1020. Number of Enclaves",
  "1035. Uncrossed Lines",
  "1044. Longest Duplicate Substring",
  "1046. Last Stone Weight",
  "1061. Lexicographically Smallest Equivalent String",
  "1071. Greatest Common Divisor of Strings",
  "1094. Car Pooling",
  "1128. Number of Equivalent Domino Pairs",
  "1137. N-th Tribonacci Number",
  "1143. Longest Common Subsequence",
  "1146. Snapshot Array",
  "1148. Article Views I",
  "1161. Maximum Level Sum of a Binary Tree",
  "1178. Number of Valid Words for Each Puzzle",
  "1189. Maximum Number of Balloons",
  "1200. Minimum Absolute Difference",
  "1207. Unique Number of Occurrences",
  "1217. Minimum Cost to Move Chips to The Same Position",
  "1232. Check If It Is a Straight Line",
  "1239. Maximum Length of a Concatenated String with Unique Characters",
  "1249. Minimum Remove to Make Valid Parentheses",
  "1254. Number of Closed Islands",
  "1275. Find Winner on a Tic Tac Toe Game",
  "1276. Number of Burgers with No Waste of Ingredients",
  "1290. Convert Binary Number in a Linked List to Integer",
  "1293. Shortest Path in a Grid with Obstacles Elimination",
  "1295. Find Numbers with Even Number of Digits",
  "1298. Maximum Candies You Can Get from Boxes",
  "1318. Minimum Flips to Make a OR b Equal to c",
  "1328. Break a Palindrome",
  "1332. Remove Palindromic Subsequences",
  "1338. Reduce Array Size to The Half",
  "1339. Maximum Product of Splitted Binary Tree",
  "1351. Count Negative Numbers in a Sorted Matrix",
  "1372. Longest ZigZag Path in a Binary Tree",
  "1378. Replace Employee ID With The Unique Identifier",
  "1399. Count Largest Group",
  "1402. Reducing Dishes",
  "1431. Kids With the Greatest Number of Candies",
  "1436. Destination City",
  "1456. Maximum Number of Vowels in a Substring of Given Length",
  "1466. Reorder Routes to Make All Paths Lead to the City Zero",
  "1480. Running Sum of 1d Array",
  "1491. Average Salary Excluding the Minimum and Maximum Salary",
  "1493. Longest Subarray of 1's After Deleting One Element",
  "1498. Number of Subsequences That Satisfy the Given Sum Condition",
  "1502. Can Make Arithmetic Progression From Sequence",
  "1527. Patients With a Condition",
  "1530. Number of Good Leaf Nodes Pairs",
  "1550. Three Consecutive Odds",
  "1572. Matrix Diagonal Sum",
  "1593. Split a String Into the Max Number of Unique Substrings",
  "1603. Design Parking System",
  "1609. Even Odd Tree",
  "1629. Slowest Key",
  "1639. Number of Ways to Form a Target String Given a Dictionary",
  "1657. Determine if Two Strings Are Close",
  "1667. Fix Names in a Table",
  "1683. Invalid Tweets",
  "1716. Calculate Money in Leetcode Bank",
  "1732. Find the Highest Altitude",
  "1757. Recyclable and Low Fat Products",
  "1768. Merge Strings Alternately",
  "1822. Sign of the Product of an Array",
  "1846. Maximum Element After Decreasing and Rearranging",
  "1857. Largest Color Value in a Directed Graph",
  "1861. Rotating the Box",
  "1903. Largest Odd Number in String",
  "1920. Build Array from Permutation",
  "1931. Painting a Grid With Three Different Colors",
  "1963. Minimum Number of Swaps to Make the String Balanced",
  "1964. Find the Longest Valid Obstacle Course at Each Position",
  "2071. Maximum Number of Tasks You Can Assign",
  "2090. K Radius Subarray Averages",
  "2094. Finding 3-Digit Even Numbers",
  "2131. Longest Palindrome by Concatenating Two Letter Words",
  "2140. Solving Questions With Brainpower",
  "2145. Count the Hidden Sequences",
  "2169. Count Operations to Obtain Zero",
  "2170. Minimum Operations to Make the Array Alternating",
  "2171. Removing Minimum Number of Magic Beans",
  "2215. Find the Difference of Two Arrays",
  "2275. Largest Combination With Bitwise AND Greater Than Zero",
  "2316. Count Unreachable Pairs of Nodes in an Undirected Graph",
  "2328. Number of Increasing Paths in a Grid",
  "2336. Smallest Number in Infinite Set",
  "2352. Equal Row and Column Pairs",
  "2359. Find Closest Node to Given Two Nodes",
  "2390. Removing Stars From a String",
  "2434. Using a Robot to Print the Lexicographically Smallest String",
  "2444. Count Subarrays With Fixed Bounds",
  "2448. Minimum Cost to Make Array Equal",
  "2466. Count Ways To Build Good Strings",
  "2491. Divide Players Into Teams of Equal Skill",
  "2563. Count the Number of Fair Pairs",
  "2583. Kth Largest Sum in a Binary Tree",
  "2610. Convert an Array Into a 2D Array With Conditions",
  "2618. Check if Object Instance of Class",
  "2619. Array Prototype Last",
  "2620. Counter",
  "2621. Sleep",
  "2622. Cache With Time Limit",
  "2623. Memoize",
  "2624. Snail Traversal",
  "2625. Flatten Deeply Nested Array",
  "2626. Array Reduce Transformation",
  "2627. Debounce",
  "2628. JSON Deep Equal",
  "2629. Function Composition",
  "2630. Memoize II",
  "2631. Group By",
  "2632. Curry",
  "2633. Convert Object to JSON String",
  "2634. Filter Elements from Array",
  "2635. Apply Transform Over Each Element in Array",
  "2636. Promise Pool",
  "2637. Promise Time Limit",
  "2641. Cousins in Binary Tree II",
  "2648. Generate Fibonacci Sequence",
  "2649. Nested Array Generator",
  "2665. Counter II",
  "2666. Allow One Function Call",
  "2667. Create Hello World Function",
  "2675. Array of Objects to Matrix",
  "2676. Throttle",
  "2677. Chunk Array",
  "2684. Maximum Number of Moves in a Grid",
  "2693. Call Function with Custom Context",
  "2694. Event Emitter",
  "2695. Array Wrapper",
  "2700. Differences Between Two Objects",
  "2703. Return Length of Arguments Passed",
  "2704. To Be Or Not To Be",
  "2705. Compact Object",
  "2715. Timeout Cancellation",
  "2799. Count Complete Subarrays in an Array",
  "2816. Double a Number Represented as a Linked List",
  "2845. Count of Interesting Subarrays",
  "2864. Maximum Odd Binary Number",
  "2894. Divisible and Non-divisible Sums Difference",
  "2900. Longest Unequal Adjacent Groups Subsequence I",
  "2901. Longest Unequal Adjacent Groups Subsequence II",
  "2918. Minimum Equal Sum of Two Arrays After Replacing Zeros",
  "2929. Distribute Candies Among Children II",
  "2942. Find Words Containing Character",
  "2962. Count Subarrays Where Max Element Appears at Least K Times",
  "3024. Type of Triangle",
  "3068. Find the Maximum Sum of Node Values",
  "3170. Lexicographically Minimum String After Removing Stars",
  "3335. Total Characters in String After Transformations I",
  "3337. Total Characters in String After Transformations II",
  "3341. Find Minimum Time to Reach Last Room I",
  "3342. Find Minimum Time to Reach Last Room II",
  "3343. Count Number of Balanced Permutations",
  "3355. Zero Array Transformation I",
  "3362. Zero Array Transformation III",
  "3392. Count Subarrays of Length Three With a Condition",
  "3403. Find the Lexicographically Largest String From the Box I",
  "3442. Maximum Difference Between Even and Odd Frequency I",
];

qs.forEach((q) => {
  const [n] = /^(\d+\.)/g.exec(q);
  const path = "./leetcode/" + n.replace(".", "_") + "*";
  const [target] = globSync(path);

  if (target) return;
  console.log(q); // 有寫過，但是沒有存檔的題目
});
